### ISSUE TITLE
ISO Connection Configuration is not picking variable names configured from csv dataset config

### ISSUE THREAD

**Issue by suresh-pandi** [tilln/jmeter-iso8583#61]
ISO Connection Configuration is not picking the JMeter variables when configured via CSV Data set config

IP address and port number was given in a text file and configured in CSV Data set config
In CSV Data set config variable names declared for ipaddress and port number

On providing the variable names in the ISO Connection configuration getting the following error in JMeter.log

2023-01-28 13:54:50,551 WARN n.c.b.j.i.Q2: (org.jpos.q2.iso.ChannelAdaptor) hostname can't be null
2023-01-28 13:54:51,551 WARN n.c.b.j.i.Q2: (org.jpos.q2.iso.ChannelAdaptor) channel-sender-jmeter-16972317-send
2023-01-28 13:54:51,551 WARN n.c.b.j.i.Q2: (org.jpos.q2.iso.ChannelAdaptor) hostname can't be null

**Expected behavior**
ISO Connection configuration should pick the values from JMeter variables if it is configured via CSV Data set.
Variable names given in Test Plan is working, only CSV Data set config is giving errors.

**Screenshots**
CSV Dataset Config
![image](https://user-images.githubusercontent.com/68426438/215258311-c08d468e-12ac-4ed7-b604-c79d986d6039.png)

ISO Connection Configuration & Log
![image](https://user-images.githubusercontent.com/68426438/215258403-77c6a583-70a5-4f92-aff3-80734f78db72.png)

**Logs**
[jmeter.log](https://github.com/tilln/jmeter-iso8583/files/10526867/jmeter.log)

JMX file:
[ISO_Bug.zip](https://github.com/tilln/jmeter-iso8583/files/10526875/ISO_Bug.zip)

**Comment by tilln** [comment]
Thanks @suresh-pandi for reporting this.

Unfortunately, what you describe as expected behaviour is not feasible to implement.
This is due to the fact that the jPOS Q2 components that the *ISO8583 Connection Configuration* represents are initialized and connected at the time the JMeter test starts but before the JMeter threads are started. 
So when the JMeter variables are populated, as in your case from the CSV file, the connection has already have to be established so that ISO messages can be sent and received over that connection. Changing the host/port at that time, dynamically, is not possible, or at least not easily at all. Keeping persistent connections may be another reason.

What I'd suggest in your case as a workaround is the following: For each host/port in your CSV data set create a separate *ISO8583 Connection Configuration* and give it a distinct "Reference/Identifier". Then list those identifiers in a CSV data set. Finally, use a JMeter variable from that CSV in the *ISO8583 Samplers* "Connection Reference/Identifier" to dynamically select one of those established connections.

Please report back of this works for you or if you need further help.
