### ISSUE TITLE
Iso trailer field issue

### ISSUE THREAD

**Issue by Chandhiramouli** [tilln/jmeter-iso8583#67]
We are using X25 channel in ISO sampler, The sample message has starting and ending value between of the ISO message.

Message format: 02<MTI><BITMAP>..........03 

**02** we gave in channel header and tried, it can able to pass the 02 in front of the iso message.
**03** we need to give in the trailer field it is not passing at the end of iso message.

**Comment by tilln** [comment]
@Chandhiramouli 
The X25Channel does not support sending a trailer (it does not override the [BaseChannel method](https://github.com/jpos/jPOS/blob/v2_1_8/jpos/src/main/java/org/jpos/iso/BaseChannel.java#L512)).
However, the BASE24Channel [does](https://github.com/jpos/jPOS/blob/v2_1_8/jpos/src/main/java/org/jpos/iso/channel/BASE24Channel.java#L85-L86) and it sends a binary `03` just as you describe.
You may want to try using this or otherwise you may have to implement your own Channel class.

**Comment by Chandhiramouli** [comment]
Hi @tilln 

We added Trailer function in X25 Channel and that was working.

**Comment by Chandhiramouli** [comment]
We added Trailer function in X25 Channel and that was working

**Comment by Chandhiramouli** [comment]
We added Trailer function in X25 Channel and that was working.
