### ISSUE TITLE
bitmap issue

### ISSUE THREAD

**Issue by mehrdad2000** [tilln/jmeter-iso8583#72]
Hi
I'm tring to send this message :

11006230A541A8E118151612345678912345673100000702090138000344230702090138070233321140121324C1080000061234560695000137123456789123456789123456789123456789400031823249812345678    0101       64Bazar                 AFRICA       THRIR108012111111111106G[APP]008      011234567891234567050800000000000000000000000000000000000000000000000000000000000000000000000000000000006002000101000000000004000032C871B0EB5A05E9B39D85716810D643190003307DDC00000000

via below test-packager.xml with jmater-iso8583 to my server.
https://github.com/jpos/jPOS/blob/master/jpos/src/main/resources/packager/iso93ascii.xml

everything is ok except bit 53
on jmeter bit 53 value is 0202010302 but after jmeter send that message value of this bit change to 0800000000

Ant idea?
Thanks

**Comment by tilln** [comment]
@mehrdad2000 
You may want to consider following the issue template and provide a minimum amount of information such as log output, incl. packager logging at debug level, otherwise no one may be willing to help out here.
What's likely is that DE53 or any of the previous fields has the wrong field packager class defined.
