### ISSUE TITLE
ISO8583 - Server mode - Sign on message issue

### ISSUE THREAD

**Issue by antonyfelix233** [tilln/jmeter-iso8583#76]
Dear @tilln 

**Issue:**
We are trying to use ISO8583 connection configuration in server mode and getting some error in the Jmeter log.
 
In Jmeter i can the 0800 message was received from the client but while unpacking/packing the 0800 getting error. due to that, the request listener not responding with 0810 message.
 
Also, please suggest how to ignore some field in request listener bsh file. For adding field we have message.set() funtions. Is there any funstion will help to ignore some field while sending 0810 message.
 
I am very new to this so bear with my question if lacked details. Thanks in advance

JMeter Log:
![JmeterLog_new](https://github.com/tilln/jmeter-iso8583/assets/155774448/03ea0637-783c-41c2-988c-2b486d144621)

Wireshark Log(Received 0800):
![WiresharkLog](https://github.com/tilln/jmeter-iso8583/assets/155774448/65f0f5dd-f168-4e06-9704-f47a0a6b562e)

Packager: (only kept the used field for your reference. while in my packager all fields available):
<img width="602" alt="Packager" src="https://github.com/tilln/jmeter-iso8583/assets/155774448/a89c7514-ad76-4779-a055-3d4364097b18">

Request listener bsh file:
<img width="257" alt="Request_Listener" src="https://github.com/tilln/jmeter-iso8583/assets/155774448/a8a18b65-6985-43cf-83a1-e9a2f485e4e1">

Message received 0800: (Placed in note pad and splitteds as fields for your reference):
<img width="656" alt="Sample0800" src="https://github.com/tilln/jmeter-iso8583/assets/155774448/5b68e428-6164-4dfd-be15-f2e2e33caa77">

Thank you in Advance

**Comment by antonyfelix233** [comment]
Added to the above i have one more doubt. in the 0800 we are receiving one header. and while sending with 0810, i've to send different header with same length. Where i can configure this in bsh file while using ISo8583 as server mode

**Comment by tilln** [comment]
Hi @antonyfelix233 
I'm currently on vacation without access to a computer, so I can only provide suggestions.

I think your issues are caused by the headers that aren't handled correctly.

You could try setting the `override-header` property. See [this issue](https://github.com/tilln/jmeter-iso8583/issues/65#issuecomment-1470544469) for reference.

In the request listener script you may want to use the `ISOMsg` methods `unset` to remove fields from the received message, if that's what you mean by "ignore".

As for the response message's header, you'll have to try one of the available options: You can set the header on the ISOMsg, it's Packager or the Channel.

**Comment by antonyfelix233** [comment]
Hi @tilln ,

Thank you for your response. I've just corrected my packager and channel used which resolved. 

Also a you mentioned, the "unset" is the one i looked for. which is also working.

Thank you so much for your advice.

Regards,
AF
