### ISSUE TITLE
edit packager configuration through jemter ui like "ISO8583 Message Component"

### ISSUE THREAD

**Issue by mehrdad2000** [tilln/jmeter-iso8583#79]
Hi

it could be better if this feature adds to "jmeter-iso8583" that able user to edit packager through jemter ui like "ISO8583 Message Component".
when select packager e.g [iso87](https://github.com/jpos/jPOS/blob/master/jpos/src/main/resources/packager/iso87ascii.xml)  [iso93](https://github.com/jpos/jPOS/blob/master/jpos/src/main/resources/packager/iso93ascii.xml) it load in gui like "ISO8583 Message Component" and when user modify it e.g change length of bit 12 it will automatically modify packager xml file.

Thanks

**Comment by tilln** [comment]
That's a nice idea, however, I think most of the time the packager configuration is created once and then not modified again, so there is typically no need for a more convenient UI.
What would complicate the UI design is that any of the field could be nested i.e. have sub-fields which may themselves be nested, so that would be difficult to express in a simple table structure.
